progetto_docker: "progetto_menu"
nome_2: "python_service_2"
destinazione: "/opt"
package_update: false
project_packages:
  - git
  - docker
  - docker-compose
  - python-pip
  - python-docker
  - python-setuptools
