---
- name: "Gestione di {{ service_name }}"

  block:
    - name: "Crea cartella di destinazione"
      ansible.builtin.file:
        path: "{{ destinazione }}/{{ service_name }}"
        state: directory
        mode: '0755'

    - name: "Copia script Python"
      ansible.builtin.copy:
        src: "{{ service_name }}.py"
        dest: "{{ destinazione }}/{{ service_name }}/{{ service_name }}.py"
        mode: '0755'

    - name: "Genera file Unit di systemd"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/service.service.j2"
        dest: "/etc/systemd/system/{{ service_name }}.service"
        mode: '0644'
      vars:
        name_service: "{{ service_name }}"
      notify:
        - Ricarica daemon systemd
        - Riavvia servizio python

    - name: "Avvia i servizi"
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: started
        enabled: true

  rescue:
    - name: "Avviso fallimento"
      ansible.builtin.debug:
        msg: "Il deployment di {{ service_name }} è fallito."
