---
- name: Riavvia container
  community.docker.docker_compose_v2:
    project_src: "{{ destinazione }}/{{ progetto_docker }}"
    state: restarted
    build: always
  become: true

- name: Ricarica systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true
