- name: Popola_db | Esecuzione script di popolamento n
  community.docker.docker_container_exec:
    container: "menu_app_container"
    command: python3 /app/popola_db.py
    chdir: /app
  register: popola_db_result
  become: true
  changed_when: false

- name: Popola_db | Mostra esito popolamento
  ansible.builtin.debug:
    var: popola_db_result.stdout_lines
